Update adding-an-existing-project-to-github-using-the-command-line.md
Removed -b main from git init because it throws following error:
error: unknown switch `b'
Also, changed git push -u origin main to git push origin master (because main is not default branch name, master is)